### ISSUE TITLE
Error PHP 7.2: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by corpsysgit** [hi-iwd/free-checkout-suite#1]
ERROR IN CHECKOUT IWD(v3.2.2): 

WARNING COUNT (): PARAMETER MUST BE AN ARRAY OR AN OBJECT THAT IMPLEMENTS COUNTABLE IN 

/vendor/iwd/opc/Plugin/Customer/Model/Address/AbstractAddress.php on line 40

Wiki:
https://wiki.php.net/rfc/counting_non_countables

**Comment by hi-iwd** [comment]
Hi!

Thank you for report. The fix was added and will be available in the next release.

**Comment by corpsysgit** [comment]
Thanks!
